version: "3.8"
services:
  vault:
    image: vault:1.5.5
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-root-token
    networks:
      default:
        aliases:
          - vault.mtls.docker

  server:
    build:
      context: ./server
    networks:
      default:
        aliases:
          - server.mtls.docker

  client:
    build:
      context: ./client
    networks:
      default:
        aliases:
          - client.mtls.docker
    environment: 
      MTLS_SERVER: "https://server.mtls.docker:8443"
    depends_on: 
      - server

